categories:
    - id: frontal
      name: 完全正脸
      path: /Users/wuzitong/Documents/数据标注/完全正脸
      shortcut: q
    - id: side
      name: 非完全正脸
      path: /Users/wuzitong/Documents/数据标注/非完全正脸
      shortcut: s
copymode: true
copytargets:
    - id: copy_1767599725833
      name: 复制1
      path: /Users/wuzitong/Documents/数据标注/xp
      shortcut: x
feedbackduration: 150
port: :12346
skipshortcut: ' '
sourcedir: /Users/wuzitong/Downloads/data-0000 (1)
undoshortcut: meta+y
