categories:
    - id: frontal
      name: 完全正脸
      path: ../output/frontal
      shortcut: "1"
    - id: side
      name: 非完全正脸
      path: ../output/side
      shortcut: "2"
copymode: true
port: :12346
skipshortcut: ' '
sourcedir: /Users/wuzitong/Downloads/data-0000 (1)
